# Generated by `itest sync`.
# You may edit these tests freely: ITest records an ownership hash and will
# only ever append new stubs, never overwrite a function you have changed.
import pytest


def test_iam_lambda_agents_role_to_logs_any():
    """Integration point 7efac0ef2e97.

    aws_iam_role.lambda_agents_role -> arn:aws:logs:us-west-1:111111111111:*
    type=iam_edge actions=['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=True
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_analysis_jobs():
    """Integration point a1cdcd6f1d1d.

    aws_iam_role.lambda_agents_role -> aws_sqs_queue.analysis_jobs
    type=iam_edge actions=['sqs:DeleteMessage', 'sqs:GetQueueAttributes', 'sqs:ReceiveMessage'] effect=Allow external=False managed=False wildcard_action=False wildcard_resource=False
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_lambda_function_alex_any():
    """Integration point 2297b815283d.

    aws_iam_role.lambda_agents_role -> arn:aws:lambda:us-west-1:111111111111:function:alex-*
    type=iam_edge actions=['lambda:InvokeFunction'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=True
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_rds_cluster_alex_aurora_cluster():
    """Integration point 5e8e502d62b7.

    aws_iam_role.lambda_agents_role -> arn:aws:rds:us-west-1:111111111111:cluster:alex-aurora-cluster
    type=iam_edge actions=['rds-data:BatchExecuteStatement', 'rds-data:BeginTransaction', 'rds-data:CommitTransaction', 'rds-data:ExecuteStatement', 'rds-data:RollbackTransaction'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=False
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_secretsmanager_secret_alex_aurora_credentials_7b1b5cc1_LvvYkh():
    """Integration point 558c220961b2.

    aws_iam_role.lambda_agents_role -> arn:aws:secretsmanager:us-west-1:111111111111:secret:alex-aurora-credentials-7b1b5cc1-LvvYkh
    type=iam_edge actions=['secretsmanager:GetSecretValue'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=False
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_s3_alex_vectors_111111111111():
    """Integration point 2267a67e8981.

    aws_iam_role.lambda_agents_role -> arn:aws:s3:::alex-vectors-111111111111
    type=iam_edge actions=['s3:GetObject', 's3:ListBucket'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=False
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_s3_alex_vectors_111111111111_any():
    """Integration point 000eee7bfa64.

    aws_iam_role.lambda_agents_role -> arn:aws:s3:::alex-vectors-111111111111/*
    type=iam_edge actions=['s3:GetObject', 's3:ListBucket'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=True
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_s3vectors_bucket_alex_vectors_111111111111_index_any():
    """Integration point 8c53a22c4c7a.

    aws_iam_role.lambda_agents_role -> arn:aws:s3vectors:us-west-1:111111111111:bucket/alex-vectors-111111111111/index/*
    type=iam_edge actions=['s3vectors:GetVectors', 's3vectors:QueryVectors'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=True
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_sagemaker_endpoint_alex_embedding_endpoint():
    """Integration point ef585ce57133.

    aws_iam_role.lambda_agents_role -> arn:aws:sagemaker:us-west-1:111111111111:endpoint/alex-embedding-endpoint
    type=iam_edge actions=['sagemaker:InvokeEndpoint'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=False
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_bedrock_foundation_model_any():
    """Integration point a570d6de7ea4.

    aws_iam_role.lambda_agents_role -> arn:aws:bedrock:*::foundation-model/*
    type=iam_edge actions=['bedrock:InvokeModel', 'bedrock:InvokeModelWithResponseStream'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=True
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_bedrock_inference_profile_any():
    """Integration point 39cb2a5298c2.

    aws_iam_role.lambda_agents_role -> arn:aws:bedrock:*:*:inference-profile/*
    type=iam_edge actions=['bedrock:InvokeModel', 'bedrock:InvokeModelWithResponseStream'] effect=Allow external=True managed=False wildcard_action=False wildcard_resource=True
    HCL: aws_iam_role_policy.lambda_agents_policy
    """
    pytest.skip("stub: implement this integration test")


def test_iam_lambda_agents_role_to_iam_policy_service_role_AWSLambdaBasicExecutionRole():
    """Integration point a54b0e0e3663.

    aws_iam_role.lambda_agents_role -> arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    type=iam_edge actions=['<unresolved>'] broad_managed_policy=False effect=Allow external=False managed=True wildcard_action=False wildcard_resource=False
    HCL: aws_iam_role_policy_attachment.lambda_agents_basic
    """
    pytest.skip("stub: implement this integration test")
