# Generated by `itest sync`.
# You may edit these tests freely: ITest records an ownership hash and will
# only ever append new stubs, never overwrite a function you have changed.
import pytest


def test_event_analysis_jobs_to_planner_event_source_mapping():
    """Integration point d22d32578df2.

    aws_sqs_queue.analysis_jobs -> aws_lambda_function.planner
    type=event_edge batch_size=1 enabled=True external=False mechanism=event_source_mapping
    HCL: aws_lambda_event_source_mapping.planner_sqs
    """
    pytest.skip("stub: implement this integration test")


def test_event_analysis_jobs_to_analysis_jobs_dlq_dlq_redrive():
    """Integration point 6a2d3c7315e6.

    aws_sqs_queue.analysis_jobs -> aws_sqs_queue.analysis_jobs_dlq
    type=event_edge external=False max_receive_count=3 mechanism=dlq_redrive
    HCL: aws_sqs_queue.analysis_jobs
    """
    pytest.skip("stub: implement this integration test")
